### ISSUE TITLE
Projectvorschlag

### ISSUE THREAD

**Issue by georglauterbach** [phip1611/multiboot2-binary-rust#1]
Hey - normalerweise auf GitHub in Englisch, aber laut Profil kann ich auch Deutsch verwenden ;)

Erstmal danke dafür, dass dieses Repo auf GitHub existiert - hat mir heute wirklich geholfen, `multiboot2` mit UEFI, GRUB2 und QEMU zum laufen zu bekommen. Ich arbeite an einem ähnlichen Projekt - OS Kernel in idiomatischem Rust - und habe mir mal ein bischen Code "geklaut" :D Gefunden habe ich das ganze über StackOverflow (tm), und fand einige der hier verwendeten Techniken - z.B. Rust selbst den Inline-Assembly-Code assemblieren und linken zu lassen - richtig gut.

Der Grund, aus dem ich diesen Issue öffne, ist der: Ich finde die Code-Quality dieses Repositorys richtig gut - die Grafiken und auch anderen Nicht-Source-Code. Das hat mich schon sehr an die Ansprüche meines Projektes erinnert. Selbst einen Kernel zu schreiben ist zwar cool, aber auch viel Aufwand. Da ich auf deiner Profil-README gelesen habe, dass du gerne low-level code schreibst, dachte ich mir, ich frage einfach mal, ob wir zusammen ein bischen an einem Kernel-Projekt hier via GitHub arbeiten wollen. Die Gründe sind durchaus simpel:

1. > I see my future in low level development and transforming ugly, undocumented code to nice, well documented and easy to use code.
   
   Vor allem was das `transforming ugly, undocumented code to nice, well documented and easy to use code.` angeht, sind wir da schon 2. Ich habe das Gefühl, es wird viel zu wenig Wert auf ordentlichen Code gelegt - geschweige denn Kommentare / darüber hinaus gehende Dokumentationen. Da spielt bei Low-Level Code eine genau so große Rolle wie bei jedem anderen Code.

2. > I'm studying computer science at TU Dresden

   Irgenwie schon lustig, denn da sind wir auch schon 2. Ich habe dieses Semester meinen Master angefangen, und belege u.a. Mikrokernbasierte Betriebssysteme :D Studeren an der TUD ist leider nicht mehr, was es vor Corona war...

3. Dieses Projekt könnte man dann später für eine Masterarbeit verwenden.
4. Man bekommt einfach größere Projekte auf die Beine, vor allem weil 4 Augen bei Problemen oft besser sind als 2.
5. Ich hätte richtig Lust, mal an einem größeren Rust-Projekt auf GitHub zu arbeiten

Mein Vorschlag ist also der: Meinen aktuellen Kernel (bitte auf den Branch achten) <https://github.com/georglauterbach/uncore/tree/feature/multiboot2> könnte ich entweder in einer GitHub-Organisation schieben oder einfach Collaborators hinzufügen - mir egal. CI war bis heute funktional - Tests in QEMU laufen noch nicht. Wenn du dich dort umschaust, wirst du sehen, dass Code-Quality oberste Priorität hat - daher ist eigentlich auch noch gar nicht so viel im Code passiert (habe mit _Phillip Oppermann_ s BlogOS angefangen, bis deren Bootloader dann irgendwie zu viel gemacht hat - ich wollte selbst was schreiben). Assembly von NASM nach GAS zu portieren ist auch langwierig :D

**Meine Frage also**: Lust, an so einem Projekt mitzuarbeiten? Natürlich alles in der Freizeit, ohne Verpflichtungen - logisch.

**Comment by phip1611** [comment]
Haha, hi @georglauterbach, das ist ja auch eine ungewöhnliche Überraschung, so ein Issue :D

> Erstmal danke dafür, dass dieses Repo auf GitHub existiert 

*freu *, genau dafür hab ich das erstellt - cool, dass es mal jemandem hilft :D 

Grundsätzlich hab ich daran großes Interesse :) Klingt cool. Lass uns mal persönlich weiter in Kontakt bleiben, hab dir eine Email geschrieben.
