### ISSUE TITLE
Will multiboot2 bring up NOVA

### ISSUE THREAD

**Issue by lonnietc** [phip1611/multiboot2-binary-rust#4]
Hello,

I am actually on the search for a a graphical boot loader as I search for something besides Grub2 which I do not really like a lot.

In as much, I have come across:

```
Quibble --- https://github.com/maharmstone/quibble

Kboot --- https://github.com/aejsmith/kboot

ReFind --- https://www.rodsbooks.com/refind/

Clover --- https://sourceforge.net/projects/cloverefiboot/files/

FreeLoader --- https://reactos.org/wiki/FreeLoader

Plop --- https://www.plop.at/en/bootmanager/intro.html
```

And of course, I am looking at your Multiboot2 as a possible option as well even though I know that it is not graphical in nature.

Any thoughts?

**Comment by phip1611** [comment]
Hi Lonnie,
I think there is a miss-understanding on your side. Multiboot2 is not a bootloader but a specification how the hand-off from a bootloader to a payload works. GRUB 2 is a multiboot (version 1 and 2) compatibly bootloader. There are others as well but I do not have experience with them, except for ipxe.

NOVA supports Multiboot2 by the way: https://github.com/udosteinberg/NOVA/blob/release-22.26.0/src/multiboot.S

For a modern solution (or modern kernel projects), I'd suggest the following:
- legacy x86 boot flows: use GRUB 2 and a multiboot2 handoff to your kernel 
- uefi x86 boot flow: use GRUB 2 for a graphical selection and then either chainload a custom-written OS loader as EFI application that bootstraps your kernel or use the same multiboot2 handoff. GRUB can hand-off to other EFI applications.

However, this needs experience in building and writing kernels and is not just an administrative work.

**Comment by lonnietc** [comment]
Hi Philipp,

Thanks for the clarification on this as it makes more sense now.
